version: '3'

services:
  db:
    image: postgres:13.0-alpine
    container_name: django_db
    restart: always
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    build: app
    container_name: django_app
    expose:
      - "8000"
    env_file:
      - db.env
    volumes:
      - static_volume:/opt/app/static

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static:ro
    depends_on:
      - django_app
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
